---
_hotel_id: UNI075
_portal_id: required-but-empty
_root_path: https://qa4.ttaws.com/rt
latitude: 43.17616
longitude: -70.60906
name: Union Bluff Hotel
email: steffan@traveltripper.io
phone_number: "--"
address:
  street1: 8 Beach St
  street2: ''
  state: Maine
  city: York Beach
  country: United States
  zip_code: 03910
